### ISSUE TITLE
Enable / Disable Stepper Motors

### ISSUE THREAD

**Issue by agent-r** [momostein/Ramps#9]
Hallo,

ist there a way to enable and disable stepper motors using this library?

Kind regards
AR

**Comment by momostein** [comment]
I don't think so, but you can try and implement it. It shouldn't be that hard. I suggest you start with learning about object oriented programming in C++.

I haven't made any significant changes to this library in 4 years, as it was only part of my final project in highschool.

**Comment by agent-r** [comment]
thx, i think i'll do that.
